server:
  port: 8088
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
    username: root
    password: root123
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      validation-query: SELECT 1
      filters: mergeStat
      max-active: 30
      initial-size: 5
      max-wait: 60000
      min-idle: 5
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 25200000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      remove-abandoned: true
      remove-abandoned-timeout-millis: 1800
      log-abandoned: true
    initialization-mode: always


mybatis:
  mapper-locations: classpath*:mappers/*.xml
#   config-location: classpath:mybatis-config.xml


#  MySQL连接数据库时，添加语句：“allowMultiQueries=true”的作用：
#  1.可以在sql语句后携带分号，实现多语句执行。
#  2.可以执行批处理，同时发出多个SQL语句。
