server:
  port: 8088
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
    username: root
    password: root123
    type: com.alibaba.druid.pool.DruidDataSource
    #  数据源其他配置
    druid:
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validaionQuery: SELECT 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      #    配置监控统计拦截的filters 去掉后监控界面sql无法统计，‘wall’用于防火墙
      filters: stat,wall,log4j #mergeStat
      maxPoolPreparedStatementPerConnectionSize: 20
      useGlobalDataSourceStat: true
      connectionProperties: druid.stat.mergeSql=true,druid.stat.slowSqlMills=500
    ###


mybatis:
  mapper-locations: classpath*:mappers/*.xml


#  MySQL连接数据库时，添加语句：“allowMultiQueries=true”的作用：
#  1.可以在sql语句后携带分号，实现多语句执行。
#  2.可以执行批处理，同时发出多个SQL语句。
